framework/file/file_test.go, framework/json/jsonutil_test.go, framework/reflects/reflects_test.go
1.  完善file单元测试			bd4d0d6
1.  删除gitignore文			e4e0749
1.  完善framework/json单元测试			1660717
1.  完善framework/reflects单元测试			8ce55d1
=> 完成framework90%功能测试

README.md
Hi @devfeel, I updated the middleware list from: https://github.com/devfeel/middleware. Please review.
=> Update middleware and fix 404 links in README.md

.travis.yml, config/configs_test.go
=> 修改travis.yml

README.md
* 新增logger.SetEnabledConsole，当设置SetDevelopmentMode时自动开启
* SetEnabledConsole：自动向console输出dotweb基础日志，便于开发人员调试阶段实时查看
* 完善日志、注释
* 2017-08-31 08:30
=> #### Version 1.0.1

README.md
* 主要新增集成基础统计数据
* 【新增】dotweb/state接口，提供基础统计数据，主要数据说明：
* 1、ServerStartTime 服务启动时间
* 2、TotalRequestCount 服务启动以来累计请求数（排除了"/dotweb/"下系统自有页面的访问数）
* 3、TotalErrorCount 服务启动以来累计错误数
* 4、IntervalRequestData 按1分钟为间隔，默认保存最近60分钟，每分钟的请求数（排除了"/dotweb/"下系统自有页面的访问数）
* 5、DetailRequestPageData 服务启动以来，每个页面的累计请求数（排除了"/dotweb/"下系统自有页面的访问数）
* 6、IntervalErrorData 按1分钟为间隔，默认保存最近60分钟，每分钟的错误数
* 7、DetailErrorPageData 服务启动以来，每个页面的累计错误数
* 8、DetailErrorData 服务启动以来，每个异常的累计数
* 9、DetailHttpCodeData 服务启动以来，每个Http状态码的累计数
* 10、可通过 {host}/dotweb/state 获取数据
* 【新增】dotweb/state/interval接口，提供按分钟级的基础数据查询
* 主要数据说明：
* 1、Time 表示查询时间的字符串，最小单位为分钟，例如：201709251200
* 2、RequestCount 单位时间内累计请求数（排除了"/dotweb/"下系统自有页面的访问数）
* 3、ErrorCount 单位时间内累计错误数
* 2017-09-25 13:00
=> #### Version 1.1

core/state.go, example/main.go
1、fixed dead lock bug when query state data
=> version 1.1-fixed dead lock bug when query state data

README.md
=> add gitter icon

README.md, config/configs.go, dotweb.go, example/config/main.go, example/tls/main.go, group.go, logger/logger.go, logger/xlog.go, middleware.go, router.go, server.go, version.MD
* 增加TLS支持
* 1)ServerConfig增加EnabledTLS\TLSCertFile\TLSKeyFile三个配置项
* 2)HttpServer增加SetEnabledTLS方法
* 3)增加example/tls目录
* 移除：移除DotWeb.StartWithConfig方法，使用配置方式时需显式调用dotweb.SetConfig方法
* 进一步完善默认日志输出
* 2017-10-07 22:00
=> 国庆迭代第三波：增加TLS支持

server.go, version.MD
add HttpServer.ServerFile for a shortcut for router.ServeFiles(path, filepath)
=> add HttpServer.ServerFile

README.md, config/configs.go, context.go, core/state.go, dotweb.go, example/main.go, feature.go, router.go, server.go, version.MD
* 主要新增设置启用详细请求数据控制，新增MethodNotAllowedHandler自定义能力，完善数据统计逻辑
* 新增设置启用详细请求数据控制：
* 1) ServerStateInfo增加EnabledDetailRequestData，用于控制是否启用详细请求数据统计
* 2) config.ServerConfig增加EnabledDetailRequestData设置，支持配置文件控制
* 3) HttpServer增加SetEnabledDetailRequestData函数，用于代码设置是否启用详细请求数据统计
* 4) fixed #63 状态数据，当url较多时，导致内存占用过大
* 新增MethodNotAllowedHandler自定义能力
* 1) dotweb增加DefaultMethodNotAllowedHandler、SetMethodNotAllowedHandle函数
* 2) fixed #64 增加MethodNotAllowed自定义处理
* 完善数据统计逻辑
* 1) 404请求不计入详细请求数据统计
* 2017-10-13 12:00
=> Version 1.3.2:主要新增设置启用详细请求数据控制，新增MethodNotAllowedHandler自定义能力，完善数据统计逻辑

README.md
=> 完善readme排版

dotweb.go, version.MD
* fixed for #70 UPDATE default http port 80 to 8080
* 增加StandardHandle，统一自定义Handle场景
* 2017-10-14 20:00
=> Version 1.3.3 - fixed for #70 & 增加StandardHandle

dotweb.go
设置app.SetEnabledLog(true)后，未记录任何日志
=> fixed #74 dotweb.SetEnabledLog 无效

context.go, example/render/main.go, render.go, version.MD
* 增强Render实现，新增多模板支持
* Context新增AddView接口，用于传入多模板
* 模板统一基于Renderer().SetTemplatePath设置的相对文件名
* 特别的：布局模板需放在第一个被解析，比如：
* ctx.AddView("_layout/layout.html")
err := ctx.View("dashbord/index.html")
* 2017-10-31 10:00
=> Version 1.3.4 - 增强Render实现，新增多模板支持

README.md
=> add cookbook link

framework/crypto/cryptos.go, framework/crypto/cryptos_test.go, framework/crypto/uuid/uuid.go, framework/crypto/uuid/uuid_test.go, request.go, version.MD
* 提升UUID性能，调整UUID算法，新增UUID包
* 提供uuid.V1\V2\V3\V4四类算法
* move example/exception to devfeel/dotweb-example
* move example/uploadfile to devfeel/dotweb-example
* add cookbook link
* 2017-11-02 14:00
=> Version 1.3.5-提升UUID性能，调整UUID算法，新增UUID包

config/configs.go, request.go, router.go, server.go, version.MD
* 提升UUID性能，调整UUID算法，新增UUID包
* HttpServer新增设置是否启用唯一请求ID，默认不开启，开启后使用32位UUID，通过ctx.RequestID获取
* 提供HttpServer.SetEnabledRequestID()函数
* 提供uuid.V1\V2\V3\V4四类算法
* move example/exception to devfeel/dotweb-example
* move example/uploadfile to devfeel/dotweb-example
* add cookbook link
* 2017-11-02 16:00
=> Version 1.3.5-提升UUID性能，HttpServer新增设置是否启用唯一请求ID

dotweb.go
=> 优化dotweb代码，更漂亮

bind.go, config/configs.go, example/bind/main.go, request.go, server.go, version.MD
* Request新增FormFiles接口，用于支持多文件上传
* fixed #92
* 2017-11-30 17:00:00
=> Version 1.3.9 - Request新增FormFiles接口，bind支持json标签

const/const.go, consts.go, core/state.go, dotweb.go, group.go, router.go, server.go, version.MD
* BUG Fixed: 修复Middleware特定场景下无效问题
* 新增dotweb.IncludeDotwebGroup，用于自动集成dotweb相关路由
* /dotweb/state 增加 ServerVersion输出
* 2018-01-22 22:00
=> Version 1.4.7 - 修复Middleware特定场景下无效问题

README.md, consts.go, example/main.go, version.MD
* 修复BUG for #112
* 调整CharsetUTF8值为"charset=utf-8"
* 2018-03-28 09:00
=> 修复BUG for #112

framework/encodes/gob/gobutil.go, version.MD
调整：Session Redis模式时，gob.EncodeMap逻辑调整，移除自动注册interface{}
=> Version 1.4.9.4

docs/GUIDE.md, example/render/main.go
add guide.md
update render example
=> add guide.md

context.go, version.MD
* fixed bug for #114 dotweb: fix error found by vet
* 2018-06-04 09:00
=> Version 1.4.9.7

config/configs.go, dotweb.go, example/main.go, framework/encodes/base64x/base64util.go, framework/encodes/base64x/base64util_test.go, framework/redis/redisutil_test.go, server.go, session/session.go, session/store_redis.go, uploadfile.go, vendor/gopkg.in/yaml.v2/LICENSE, vendor/gopkg.in/yaml.v2/README.md, vendor/gopkg.in/yaml.v2/apic.go, vendor/gopkg.in/yaml.v2/decode.go, vendor/gopkg.in/yaml.v2/decode_test.go, vendor/gopkg.in/yaml.v2/emitterc.go, vendor/gopkg.in/yaml.v2/encode.go, vendor/gopkg.in/yaml.v2/encode_test.go, vendor/gopkg.in/yaml.v2/example_embedded_test.go, vendor/gopkg.in/yaml.v2/parserc.go, vendor/gopkg.in/yaml.v2/readerc.go, vendor/gopkg.in/yaml.v2/resolve.go, vendor/gopkg.in/yaml.v2/scannerc.go, vendor/gopkg.in/yaml.v2/sorter.go, vendor/gopkg.in/yaml.v2/suite_test.go, vendor/gopkg.in/yaml.v2/writerc.go, vendor/gopkg.in/yaml.v2/yaml.go, vendor/gopkg.in/yaml.v2/yamlh.go, vendor/gopkg.in/yaml.v2/yamlprivateh.go, version.MD
* New feature：UploadFile.RandomFileName used to get random file name from uuid
* New feature: encodes.base64x used to quickly use base64 EncodeString and DecodeString
* New feature: session.NewRedisConfig use to create redis session config include serverUrl and storeKeyPre
* if you set custom storeKeyPre, it will be store key start with custom set, default is "dotweb:session:"
* 2018-06-08 17:00
=> Version 1.5

logger/xlog.go, version.MD
* Fixed Bug: double sprintf on logger.xlog
* 2018-06-15 14:00
=> Version 1.5.1

README.md
=> add project list

framework/hystrix/hystrix.go, version.MD
* BugFixed: hystrix add doCleanHistoryCounter, used to clean history counter
* 2018-08-18 10:00
=> Version 1.5.6.1

README.md, consts.go, dotweb.go, version.MD
* Add DotWeb Mock log
* Update README
* 2018-08-22 10:00
=> Version 1.5.7.1

mock.go, version.MD
* Add DotWeb Mock log
* Mock support Register\RegisterString\RegisterJson
* Update README
* 2018-08-22 10:00
=> Version 1.5.7.1 - Mock support Register\RegisterString\RegisterJson

dotweb.go, example/main.go, version.MD
* Fixed Bug: App.RunMode always is RunMode_Development
* Update: Add RunMode log output
* 2018-08-24 10:00
=> Version 1.5.7.2 - Fixed Bug

middleware.go, version.MD
* Fixed Bug: return err from Next() in RequestLogMiddleware & TimeoutHookMiddleware
* 2018-08-30 10:00
=> Version 1.5.7.5 - Fixed Bug

config/configs.go, session/session.go, session/store_runtime.go, version.MD
* Improve Comments about session Maxlifetime
* Session.StoreConfig.Maxlifetime: session life time, with second
* 2018-09-20 15:00
=> #### Version 1.5.7.8

consts.go
* Architecture: add dotweb_sysgroup.go to implement IncludeDotwebGroup
* New Feature: add /virtualPath/dotweb/routers to list all router express
* New Feature: add Router.GetAllRouterExpress to return router.allRouterExpress
* About dotweb.IncludeDotwebGroup:
- if use dotweb.New(), in default it will not call IncludeDotwebGroup
- if use dotweb.Classic(), in default it will call IncludeDotwebGroup
* 2019-06-22 16:00
=> Version 1.6.4 - add dotweb_sysgroup.go and /virtualPath/dotweb/routers and Router.GetAllRouterExpress

go.mod, go.sum, version.MD
* New Feature: Add Go Module Support
* 2019-06-29 15:00 at ShangHai.Home
=> Version 1.6.7 - Add Go Module Support

README.md, consts.go
* New Feature: Add Go Module Support
* Architecture: Remove vendor
* 2019-06-29 15:00 at ShangHai.Home
=> Version 1.6.7 - Add Go Module Support & Remove vendor

consts.go, dotweb.go, dotweb_test.go, example/middleware/main.go, middleware.go, plugin.go, plugin_test.go, version.MD
* New Feature: 增加插件机制-Plugin，随App启动一起执行，不会阻塞App启动过程，如需持续运行，在Plugin的Run中自行处理即可。
* Architecture: 修正BaseMiddlware命名错误，增加BaseMiddleware，保留BaseMiddlware至2.0版本前
* About Plugin:
- 通过dotweb.UsePlugin注册插件
- 自定义插件需事先Plugin接口
- 即将发布集成插件 - 监控配置文件变化热重启插件
* 2019-07-12 12:00 at ShangHai
=> Version 1.6.9 - 增加插件机制

consts.go, dotweb_sysgroup.go, framework/stringx/stringx.go, framework/stringx/stringx_test.go, version.MD
* New Feature: 新增stringx.CompletionRight\CompletionLeft，用于指定长度两侧补齐字符串
* Update: 完善dotweb/routers系统页，输出method+router格式，类似："GET         /dotweb/routers"
* 2019-07-27 08:00 at ShangHai
=> Version 1.7.1 - 新增stringx.CompletionRight\CompletionLeft,完善dotweb/routers系统页

consts.go, core/htmlx.go, core/state.go, dotweb_sysgroup.go, version.MD
* Opt: 优化系统路由dotweb/state、dotweb/routers展现方式，以方便阅读的表格形式输出
* Feature: 新增core.TableHtml\core.CreateTableHtml()用于生成相关Html代码
* About:
- 可访问dotweb/state查看当前实例运行时信息
- 可访问dotweb/routers查看当前实例注册的所有路由信息
* 2019-11-12 18:00 at ShangHai
=> 优化系统路由dotweb/state、dotweb/routers展现方式

tree.go, version.MD
* Opt: optimize tree.go
* Opt: Fix some panic information when a 'catch-all' wildcard conflict occurs. 
* Opt: use maxParamCount const instead of magic number.
* Opt: optimize countParams.
* Opt: optimize incrementChildPrio.
* Opt: comment style fixes.
* Opt: improve param name check.
* Opt: fix maxParams bug.
* 2019-11-19 12:00 at ShangHai
=> optimize router code

core/htmlx.go, core/state.go, dotweb_sysgroup.go, version.MD
* Opt: optimize html create code
* Opt: optimize core.CreateTablePart\core.CreateTableHtml\core.CreateHtml
* 2019-11-20 07:00 at ShangHai
=> optimize html create code

consts.go, dotweb.go, example/main.go, server.go, version.MD
* fix: fix error when set HttpServer.SetEnabledGzip(true)
* add Happy 6.1 print
* 2020-06-01 23:00 at ShangHai
=> Version 1.7.12 - fix bug & happy 6.1！

consts.go
####Version 1.7.16
* Bug fix: fix middleware chain misbehaving in netsed groups
* Tips: for issue #234, thanks for @live's code
* 2021-01-24 22:00 at ShangHai
=> Version 1.7.16: replace *HttpContext to Context interface & fix middleware chain misbehaving in netsed groups

consts.go, context.go, example/main.go, session/session.go, session/sessionstate.go, version.MD
####Version 1.7.21
* feature: add SessionManager.RemoveSessionState to delete the session state associated with a specific session ID
* feature: add HttpContext.DestorySession() to delete all contents of the session and set the sessionId to empty
* For my birthday!
* 2023-04-15 16:00 at ShangHai
=> For my birthday! Update to Version 1.7.21
