devfeel/dotweb

- consts_test.go
consts_test.go is not neccesary
> remove consts_test.go

- context_test.go
调整context.go中WriteString用例
原来传入为byte数组,导致断言错误.
> 调整context.go用例

- core/context.go
- core/state.go
- core/state_test.go
- dotweb.go
- example/main.go
- response.go
- router.go
- server.go
- version.MD
* 主要新增集成基础统计数据
* 【新增】dotweb/state接口，提供基础统计数据，主要数据说明：
* 1、ServerStartTime 服务启动时间
* 2、TotalRequestCount 服务启动以来累计请求数（排除了"/dotweb/"下系统自有页面的访问数）
* 3、TotalErrorCount 服务启动以来累计错误数
* 4、IntervalRequestData 按1分钟为间隔，默认保存最近60分钟，每分钟的请求数（排除了"/dotweb/"下系统自有页面的访问数）
* 5、DetailRequestPageData 服务启动以来，每个页面的累计请求数（排除了"/dotweb/"下系统自有页面的访问数）
* 6、IntervalErrorData 按1分钟为间隔，默认保存最近60分钟，每分钟的错误数
* 7、DetailErrorPageData 服务启动以来，每个页面的累计错误数
* 8、DetailErrorData 服务启动以来，每个异常的累计数
* 9、DetailHttpCodeData 服务启动以来，每个Http状态码的累计数
* 10、可通过 {host}/dotweb/state 获取数据
* 【新增】dotweb/state/interval接口，提供按分钟级的基础数据查询
* 主要数据说明：
* 1、Time 表示查询时间的字符串，最小单位为分钟，例如：201709251200
* 2、RequestCount 单位时间内累计请求数（排除了"/dotweb/"下系统自有页面的访问数）
* 3、ErrorCount 单位时间内累计错误数
* 2017-09-25 13:00
> Version 1.1 - 新增集成基础统计数据

- context.go
测试了下，仅在WriteString存在。
原因为未显式设置MIME类型导致。、
WriteString默认设置为MIMETextPlainCharsetUTF8
已修复。
> fixed #72 【BUG】app.HttpServer.SetEnabledGzip(true)设置gzip压缩后，访问压缩文件

- README.md
- dotweb.go
- example/start/main.go
- logger/logger.go
- version.MD
Version 1.3.7
* 新增Classic初始化App方式，调整New初始化内容
* 调整日志启用开关默认为false，可以通过SetEnabledLog(true)或者SetDevelopmentMode()启用
* dotweb.New()仅初始化必要的组件，移除打印Logo，移除启动日志
* dotweb.Classic()方式下，默认启用日志，默认启用RequestLog中间件，默认打印logo以及启动日志
* dotweb.SetDevelopmentMode()在原有启用屏幕打印的基础上，增加默认开启日志开关
* 新增 example/start
* 2017-11-10 21:30
> 新增Classic初始化App方式,调整New初始化内容,调整日志启用开关默认为false

- README.md
- bind.go
- context.go
- example/bind/main.go
- request.go
- version.MD
* 强化Bind能力，添加BindJsonBody接口，不对Content-Type进行判定，直接获取req.Body进行json序列化
* 基础Bind机制：
1)如果识别到Content-Type = application/json  会尝试使用json序列化到struct
2)如果识别到Content-Type = application/xml  会尝试使用xml序列化到struct
3)非以上类型，会默认识别form的key/value模式匹配
* Context.Request()新增PostValues接口，包含 POST, PATCH, or PUT请求集合，以map[string][]string返回
* 更正Readme部分文字描述
* 完善example/bind
* 2017-12-29 16:00:00
> Develop - 强化Bind能力,新增PostValues接口,更正Readme部分文字描述

- context.go
- dotweb.go
- example/middleware/main.go
- group.go
- middleware.go
- router.go
- router_test.go
- server_test.go
- tree.go
- version.MD
* dotweb新增ExcludeUse接口，用于设置指定排除路由的中间件
* 调整dotweb部分内部函数名称
* 重构Middleware实现,优化代码结构，使流程更清晰
* Node新增AppMiddlewares与GroupMiddlewares，用于存储App级、Group级的中间件实例
* Middleware新增Exclude相关接口
* Exclude(routers ...string)函数，用于指定不生效的路由
* HasExclude() bool函数，用于判定当前中间件实例是否存在排除路由
* ExistsExcludeRouter(router string) bool函数，用于判定当前中间件实例的排除路由中是否存在指定路由
* middleware执行优先级：
- 优先级1：app级别middleware
- 优先级2：group级别middleware
- 优先级：router级别middleware
* 更新example/middleware
* 2018-01-01 23:00:00
> Develop - dotweb新增ExcludeUse接口，重构Middleware实现

- README.md
- context.go
- example/appcontext/main.go
- example/bind/main.go
- example/cache/main.go
- example/config/main.go
- example/httpmodule/main.go
- example/main.go
- example/middleware/main.go
- example/router/main.go
- example/session/main.go
- example/static/main.go
- version.MD
* Context新增QueryInt\QueryInt64接口，用于简化获取Int类型的Get参数，如果参数未传入或不是合法整形，返回0
* Context接口调整：除Write外，其他WriteXXX接口，返回值从(int, error)调整为error
* 带来的变化：
```
app.HttpServer.GET("/index", func(ctx dotweb.Context) error{
_, err := ctx.WriteString("welcome to my first web!")
return err
})
```
简化为
```
app.HttpServer.GET("/index", func(ctx dotweb.Context) error{
return ctx.WriteString("welcome to my first web!")
})
```
* 同步更新example代码
* 2018-01-03 22:00
> Develop - 完善HttpContext，提升易用性

- dotweb.go
- example/middleware/main.go
- framework/file/file.go
- framework/file/file_test.go
- uploadfile.go
- version.MD
* 调整dotweb内部路由注册逻辑，New模式默认不开启，Classic模式默认开启，可通过app.UseDotwebRouter手动开启
* 修复 issue #100, 解决特定场景下Exclude不生效问题
* Use filepath.Ext to replace file.GetFileExt, update for issue #99
* 移除 framework/file.GetFileExt 函数
* 同步更新example代码
* 2018-01-07 22:00
> Version 1.4.3 - BUG修复，优化代码

- bind.go
- example/static/main.go
- version.MD
* 调整Bind模块内部获取req.Body为HttpContext.PostBody,避免因为Bind后无法再次获取Post内容
* 完善debug log 输出
* 更新example/static, 该示例目前为实现一个纯静态文件服务器功能
* * 2018-01-08 12:00
> Version 1.4.4 - 调整Bind模块实现，完善日志，增加纯静态文件服务器示例

- README.md
- consts.go
- uploadfile.go
- version.MD
* BUG Fixed: UploadFile废弃Bytes接口，新增ReadBytes接口，用于返回上传文件本身
* 需要特别注意，由于io.read具有一次性特性，UploadFile.SaveFile与UploadFile.ReadBytes只能使用其中一个，另外一个将无法正常获取数据
* 增加dotweb.Version，用于输出框架版本号
* Readme增加基于dotweb与mapper实现的yulibaozi.com博客源码链接
* 2018-01-21 09:00
> Version 1.4.6 BUG Fixed & dotweb.Version

- context.go
- core/concurrenceMap.go
- dotweb.go
- example/basemiddleware/main.go
- framework/convert/convert.go
- middleware.go
- vendor/gopkg.in/yaml.v2/.travis.yml
- vendor/gopkg.in/yaml.v2/LICENSE
- vendor/gopkg.in/yaml.v2/LICENSE.libyaml
- vendor/gopkg.in/yaml.v2/README.md
- vendor/gopkg.in/yaml.v2/apic.go
- vendor/gopkg.in/yaml.v2/decode.go
- vendor/gopkg.in/yaml.v2/decode_test.go
- vendor/gopkg.in/yaml.v2/emitterc.go
- vendor/gopkg.in/yaml.v2/encode.go
- vendor/gopkg.in/yaml.v2/encode_test.go
- vendor/gopkg.in/yaml.v2/example_embedded_test.go
- vendor/gopkg.in/yaml.v2/parserc.go
- vendor/gopkg.in/yaml.v2/readerc.go
- vendor/gopkg.in/yaml.v2/resolve.go
- vendor/gopkg.in/yaml.v2/scannerc.go
- vendor/gopkg.in/yaml.v2/sorter.go
- vendor/gopkg.in/yaml.v2/suite_test.go
- vendor/gopkg.in/yaml.v2/writerc.go
- vendor/gopkg.in/yaml.v2/yaml.go
- vendor/gopkg.in/yaml.v2/yamlh.go
- vendor/gopkg.in/yaml.v2/yamlprivateh.go
- version.MD
* 新增: ConcurrenceMap增加GetTimeDuration接口，用于直接返回time.Duration类型数据
* 新增: ReadonlyMap增加GetTimeDuration接口，用于直接返回time.Duration类型数据
* 新增: dotweb增加UseTimeoutHook接口，用于设置请求处理超过设置时间钩子函数
* 调整：dotweb内建集成三类中间件，无需单独引用Middleware库
* RequestLogMiddleware
* TimeoutHookMiddleware
* dotweb.SetExceptionHandle
* 新增 example/basemiddleware
* 集成vendor: gopkg.in/yaml.v2
* 2018-02-12 12:00
> 新增 UseTimeoutHook\GetTimeDuration接口，内建三类基础middleware

- .travis.yml
- dotweb.go
- example/start/main.go
- logger/logger.go
- uploadfile.go
- version.MD
* 重要：go版本适配升级为1.9+
* 调整UploadFile.Size实现方法，直接返回Header.Size数据
* 调整dotweb.Classic签名为Classic(logPath string),若传入logPath为空，则默认以"bin-root/logs"为日志目录
* 新增dotweb.ClassicWithConf(config *config.Config),支持初始化传入config设置
* 调整默认Log目录由"bin-root"为"bin-root/logs"
* 2018-04-24 08:30
> #### Version 1.4.9.3

- cache/runtime/cache_runtime.go
- cache/runtime/cache_runtime_test.go
- const/const.go
- core/state.go
- dotweb.go
- response.go
- session/store_redis.go
- version.MD
* 调整: dotweb.Classic移除自动UseRequestLog逻辑
* 调整：Session Redis模式时，新增sessionReExpire用于重置有效期，避免调用SessionUpdate导致不必要的redis数据交换
* 调整：Cache.Runtime调整map为sync.Map
* 状态页：访问/dotweb/state时增加CurrentTime字段输出
* BUG： 修正Reponse自动释放时未重置body字段，导致内存溢出BUG
* 2018-05-10 13:30
> Version 1.4.9.4

- dotweb.go
- example/render/main.go
- render.go
- server.go
- version.MD
* New feature: dotweb.innerRenderer add cache mode, default is enabled
* New feature: dotweb.innerRenderer add NewInnerRendererNoCache() used to disabled cache
* Update for app run_mode: if it's develop run mode, the default renderer will use no cache mode
* 2018-06-22 14:00
> Version 1.5.2

- config/configs.go
- consts.go
- dotweb.go
- feature.go
- logger/logger.go
- logger/xlog.go
- server.go
- session/session.go
- version.MD
* New feature: Session.StoreConfig support CookieName, used to set custom cookie name which sessionid store, default is dotweb_sessionId
* Update: Config.SessionNode add CookieName, used to set custom cookie name which sessionid store
* Update: default log format update to "Time [LogLevel] [FileName:Line] Content"
* BugFixed: remove init session which exec on dotweb.initAppConfig
* 2018-08-02 15:00
> Version 1.5.4

- core/state.go
- core/state_test.go
- server.go
- version.MD
* New feature: /dotweb/state add CurrentRequestCount data
* Update: improve 30% performance on app's metric
* 2018-08-09 15:00
> Version 1.5.5

- config/configs.go
- framework/hystrix/counter.go
- framework/hystrix/hystrix.go
- server.go
- session/session.go
- session/store_redis.go
- version.MD
* New feature: add hystrix module, now is used to auto switch to backup redis session store
* New feature: Session.StoreConfig support BackupServerUrl, used to store session when default ServerIP redis is not available
* Detail:
- hystrix default MaxFailedNumber is 20 per 2 minutes
- Example:
```
sessionConf := session.NewDefaultRedisConfig("redis://10.10.0.1:6322/1")
sessionConf.BackupServerUrl = "redis://10.10.0.1:6379/1"
```
* 2018-08-09 15:00
> Version 1.5.6

- router.go
* New Feature: Add HttpServer.VirtualPath, used to set virtual path when deploy on no root path
* Detail:
- when set virtual path "/vpath", if set route "/index", it will auto register "vpath/index"
- in effect on group & route
* 2018-08-24 19:00
> Version 1.5.7.3 - Add HttpServer.VirtualPath

- core/state.go
- framework/sysx/sysx.go
- router.go
- version.MD
* Fixed Bug: Remove auto set NotFound http status when happened 404, if auto set, it will ignore any ContentType set
* For issue #149 router middleware handle http 404,405. cann`t response content-type:application/json
* Thanks for @lyw1995
* 2018-08-28 13:00
> Version 1.5.7.4 - Bug Fixed

- consts.go
* Fixed Bug: return err from Next() in RequestLogMiddleware & TimeoutHookMiddleware
* 2018-08-30 10:00
> Version 1.5.7.5 - return err from Next()

- example/render/main.go
- example/render/testview.html
- render.go
- version.MD
* New Feature: Add Renderer.RegisterTemplateFunc, used to register template func in renderer
* Detail:
- now inner support inner func like unescaped
- you can view example on example/render
* Example:
``` golang
app.HttpServer.Renderer().RegisterTemplateFunc("echo", func(x string) interface{}{
return "echo:" + x
})
```
* 2018-09-07
> Version 1.5.7.6 - Add Renderer.RegisterTemplateFunc

- config/configs.go
- consts.go
- example/router/main.go
- router.go
- server.go
- version.MD
* New Feature: Add HttpServer.SetEnabledAutoOPTIONS, used to set route use auto options
* Detail:
- ignore auto set if register router is options method
- you can view example on example/router
* Example:
``` golang
app.HttpServer.SetEnabledAutoOPTIONS(true)
```
* Fixed Bug: When use HttpServer.SetEnabledAutoHead, ignore auto set if register router is head method
* Log output: Add debug log when AutoOPTIONS and AutoHead doing
* Like:
~~~
2018-09-19 15:44:42.8189 [DEBUG] [router.go:437] DotWeb:Router:RegisterRoute success [GET] [/] [main.Index]
2018-09-19 15:44:42.8199 [DEBUG] [router.go:462] DotWeb:Router:RegisterRoute AutoHead success [HEAD] [/] [main.Index]
2018-09-19 15:44:42.8199 [DEBUG] [router.go:474] DotWeb:Router:RegisterRoute AutoOPTIONS success [OPTIONS] [/] [main.Index]
~~~
* …
> #### Version 1.5.7.7

- example/bind/main.go
- server.go
- version.MD
* New Feature: Add HttpServer.SetBinder, used to set custom Binder on HttpServer
* Detail:
- Custom binder must implement dotweb.Binder interface
* Example:
``` golang
app.HttpServer.SetBinder(newUserBinder())
```
* update example/bind
* 2018-10-24 21:00
> Version 1.5.8 - Add HttpServer.SetBinder

- config/configs.go
- dotweb.go
- group.go
- request.go
- router.go
- server.go
- version.MD
* New Feature: Add HttpServer.SetEnabledStaticFileMiddleware, used to set flag which enabled or disabled middleware for static-file route
* Detail:
- if enabled, when visit static file route, will use middlewares like other router
- the execute order: App -> Group -> Router
- default is not enabled
* Example:
``` golang
app.HttpServer.SetEnabledStaticFileMiddleware(true)
```
* New Feature: Add Group.ServerFile used to registe static file router in group
* New Feature: Add ping check when init redis session, if can not ping successful, it will panic error info, like "panic: redis session [redis] ping error"
* update dotweb-example/static
* 2018-10-30 15:00
> Version 1.5.9 - Add HttpServer.SetEnabledStaticFileMiddleware & Group.ServerFile & Ping Check

- consts.go
- example/main.go
- request.go
- router.go
- version.MD
* New Feature: Add Request.RealIP used to returns the first ip from 'X-Forwarded-For' or 'X-Real-IP' header key, fixed for #164
* New Feature: route.ServerFile support '*filepath' or '/*', to simplify register static file router, fixed for #125
* Example:
``` golang
app.HttpServer.ServerFile("/*", "D:/gotmp")
```
* update example/main
* 2018-12-03 15:00
> Add Request.RealIP and route.ServerFile support ''/*filepath' or '/*'

- README.md
- example/middleware/main.go
- request.go
- response.go
- version.MD
* Fixed Bug: Request.IsAJAX check X-Requested-With Contains XMLHttpRequest
* New Feature: Response support http2 Push
* How To:
- how to query slow response in your app?
~~~go
func main() {
app := dotweb.Classic("/home/logs/wwwroot/")
// deal slow response, use default handler
// default Handler will write timeout-response in dotweb's log file
// also you can implement your own handlers, like write logs with http api
app.UseTimeoutHook(dotweb.DefaultTimeoutHookHandler, time.Second * 10)
app.HttpServer.GET("/index", func(ctx dotweb.Context) error{
return ctx.WriteString("welcome to my first web!")
})
//begin server
err := app.StartServer(80)
fmt.Println("dotweb.StartServer error => ", err)
}
~~~
* 2019-01-02 18:00
> Fixed Bug & support http2 Push

- README.md
- router.go
- server.go
- version.MD
* New Feature: HttpServer & Router add RegisterServerFile use to register ServerFile router with routeMethod method on http.FileServer
* Update: ServerFile add support for EnabledAutoHEAD\EnabledAutoOPTIONS
* Detail:
- when use ServerFile, default routeMethod is GET
- you can use RegisterServerFile specify other HttpMethod, like "POST"
* Example:
``` golang
server.RegisterServerFile(dotweb.RouteMethod_POST, "/dst/*", "/home/www/")
```
* How To:
- how to add support "HEAD" method for all requests in your httpserver?
~~~go
func main() {
app := dotweb.Classic("/home/logs/wwwroot/")
// if use this, all router will auto add "HEAD" method support
// default is false
app.HttpServer.SetEnabledAutoHEAD(true)
app.HttpServer.GET("/index", func(ctx dotweb.Context) error{
return …
> add RegisterServerFile & support EnabledAutoHEAD\EnabledAutoOPTIONS in ServerFile 

- consts.go
- example/router/main.go
- request.go
- router.go
- tree.go
- version.MD
* New Feature: RouterNode add RouterNode.Path() to get routing path for the request
* Detail:
- you can use ctx.RouterNode().Path() to get routing path for the request
- you can use ctx.HttpServer().Router().MatchPath to match request and routing path
* Demo:
~~~go
func main() {
app := dotweb.Classic("/home/logs/wwwroot/")
// if use this, all router will auto add "HEAD" method support
// default is false
app.HttpServer.SetEnabledAutoHEAD(true)
app.HttpServer.GET("/index", func(ctx dotweb.Context) error{
flag := ctx.HttpServer().Router().MatchPath(ctx, "/index")
return ctx.WriteString("welcome to my first web!" + ctx.RouterNode().Path() + " - " + fmt.Sprint(flag))
})
err := app.StartServer(80)
fmt.Println("dotweb.StartServer error => ", err)
}
~~~
* 2019-02-12 16:00
> Add RouterNode.Path()

- framework/crypto/cryptos.go
- framework/crypto/cryptos_test.go
- version.MD
* Bug fixed: cryptos.GetRandString used to returns randominzed string with given length
* Detail:
- default character set is "0123456789abcdefghijklmnopqrstuvwxyz"
* Demo:
~~~go
func main() {
fmt.Println(cryptos.GetRandString(10))
}
~~~
* 2019-02-20 14:00
> Bug fixed for cryptos.GetRandString

- logger/logger.go
* Architecture: move logger.Logger() to DotWeb.Logger()
* Architecture: add HttpServer.Logger who is a shortcut for DotWeb.Logger()
* Architecture: remove logger.Logger()
* How to use dotweb.Logger in your app:
~~~go
func TestLog(ctx dotweb.Context) error {
ctx.HttpServer().Logger().Info(dotweb.LogTarget_Default, "test log")
return ctx.WriteString("log page")
}
~~~
* 2019-06-13 12:00
> #### Version 1.6.3

- dotweb.go
- dotweb_sysgroup.go
- router.go
- version.MD
* Architecture: add dotweb_sysgroup.go to implement IncludeDotwebGroup
* New Feature: add /virtualPath/dotweb/routers to list all router express
* New Feature: add Router.GetAllRouterExpress to return router.allRouterExpress
* About dotweb.IncludeDotwebGroup:
- if use dotweb.New(), in default it will not call IncludeDotwebGroup
- if use dotweb.Classic(), in default it will call IncludeDotwebGroup
* 2019-06-22 16:00
> Version 1.6.4 - add dotweb_sysgroup.go and /virtualPath/dotweb/routers and Router.GetAllRouterExpress

- consts.go
- core/state.go
- dotweb.go
- dotweb_sysgroup.go
- router.go
- server.go
- version.MD
* Architecture: move core.GlobalState to dotweb.StateInfo()
* Architecture: add HttpServer.StateInfo() who is a shortcut for DotWeb.StateInfo()
* Remove: remove unused property valueNodePool in router
* About dotweb.StateInfo:
- you can use ctx.HttpServer().StateInfo() to get this object
- you can visit /virtualPath/dotweb/state to list all state info
* 2019-06-26 08:00
> Version 1.6.5 - add dotweb.StateInfo() & remove valueNodePool

- consts.go
- logger/logger.go
- logger/xlog.go
- version.MD
* New Feature: Add AccessLog middleware for logging HTTP requests in the Apache Common Log Format.
* New Feature: Add Raw() in dotweb.Logger
* About AccessLog:
- implement the Apache Common Log Format
- log file name like "dotweb_accesslog_2017_06_09.log"
- log-example: 127.0.0.1 - frank [10/Oct/2000:13:55:36 -0700] "GET /apache_pb.gif HTTP/1.0" 200 2326
* How to use AccessLog middleware:
~~~ go
app.Use(accesslog.Middleware())
server.GET("/", Index).Use(accesslog.Middleware())
~~~
* 2019-06-27 23:00 at 深圳华安大酒店
> Version 1.6.6 -  Add AccessLog middleware for logging HTTP requests in the Apache Common Log

- vendor/golang.org/x/net/LICENSE
- vendor/golang.org/x/net/PATENTS
- vendor/golang.org/x/net/websocket/client.go
- vendor/golang.org/x/net/websocket/dial.go
- vendor/golang.org/x/net/websocket/hybi.go
- vendor/golang.org/x/net/websocket/server.go
- vendor/golang.org/x/net/websocket/websocket.go
* Architecture: Remove OfflineServer
* Example: Remove render\developmode\start examples
* Bug fix: update latest tag to v1.6.8 for go modules
* About examples:
- You can visit https://github.com/devfeel/dotweb-example to know more examples for dotweb.
* 2019-06-29 21:00 at ShangHai.Home
> Version 1.6.8 - Remove OfflineServer & Remove render\developmode\start examples

- go.mod
- go.sum
* Architecture: Remove OfflineServer
* Example: Remove render\developmode\start examples
* Bug fix: update latest tag to v1.6.8 for go modules
* About examples:
- You can visit https://github.com/devfeel/dotweb-example to know more examples for dotweb.
* 2019-06-29 21:00 at ShangHai.Home
> Version 1.6.8 - Support Go Modules & Remove OfflineServer & Remove render\developmode\start examples

- config/configs.go
- consts.go
- dotweb.go
- dotweb_test.go
- plugin.go
- plugin_test.go
- version.MD
* New Feature: 新增NotifyPlugin插件，默认集成监控配置文件变化热重启
* New Feature: 新增DotWeb.ReSetConfig用于运行时重载配置
* About NotifyPlugin：
- 通过NewDefaultNotifyPlugin创建默认集成的NotifyPlugin
- 仅当Dotweb通过配置文件启动方式下有效，监测默认的配置文件
- 当热重启配置文件时，Dotweb本身监听端口以及pprod设置不会重载
- 感谢@地蛋对该插件的支持
* 2019-07-22 14:00 at ShangHai
> Version 1.7.0 - Add DotWeb.ReSetConfig & NotifyPlugin

- config/configs.go
- context.go
- dotweb_test.go
- example/main.go
- request.go
- router.go
- server.go
The situation that if we do not limit the request's body size,the func ioutil.ReadAll(req.Body) will caused OOM very soon if body size is very large.
To limit the request's body size to be read
which can avoid unexpected or malicious request to cause the service's OOM
- default is 32 << 20 (32 mb)
- -1 : unlimted
- 0 : use default value
- else: use other value
> add request max body size limit 

- errors.go
- router.go
- server.go
- version.MD
* New Feature: HttpServer.RegisterServerFile增加excludeExtension参数，用于设置不希望被访问的文件后缀名
* Update: 增加ErrNotFound
* About HttpServer.RegisterServerFile:
- Demo: server.RegisterServerFile(RouteMethod_GET, "/src/*", "/var/www", nil)
- Demo: server.RegisterServerFile(RouteMethod_GET, "/src/*filepath", "/var/www", []string{".zip", ".rar"})
- 当设置excludeExtension为nil时，可访问所有文件
- 本次更新涉及API变更
* Fixed for issue #125 & #212
* 2019-11-04 01:00 at ShangHai
> HttpServer.RegisterServerFile增加excludeExtension参数

- consts.go
- example/router/main.go
- router.go
- server.go
- version.MD
* Feature: Router增加RegisterHandlerFunc,用于支持注册go原生http.HandlerFunc形式的函数
* Feature: HttpServer增加RegisterHandlerFunc与RegisterRoute
* Opt: Router增加transferHandlerFunc、transferStaticFileHandler辅助函数
* Example: 修改example/router增加RegisterHandlerFunc示例
* About RegisterHandlerFunc
- Func: RegisterHandlerFunc(routeMethod string, path string, handler http.HandlerFunc) RouterNode
* How to use RegisterHandlerFunc:
~~~ go
func HandlerFunc(w http.ResponseWriter, r *http.Request){
w.Write([]byte("go raw http func"))
}
server.RegisterHandlerFunc("GET", "/h/func", HandlerFunc)
~~~
* 2019-11-07 01:00 at ShangHai
> 新增支持注册go原生http.HandlerFunc形式的函数

- consts.go
- example/router/main.go
- router.go
- version.MD
* Fix: 修复在调用SetMethodNotAllowedHandle时修改StatusCode无效问题
* Opt: 将路由阶段设置405代码逻辑移除，相关逻辑在DefaultMethodNotAllowedHandler实现
* About MethodNotAllowedHandle:
- 默认使用DefaultMethodNotAllowedHandler
- 如调用SetMethodNotAllowedHandle，则使用用户代码覆盖DefaultMethodNotAllowedHandler
* How to use SetMethodNotAllowedHandle:
~~~ go
app.SetMethodNotAllowedHandle(func(ctx dotweb.Context){
ctx.Redirect(301, "/")
})
~~~
* 2019-11-10 00:00 at ShangHai
> 修复在调用SetMethodNotAllowedHandle时修改StatusCode无效问题

- consts.go
- context.go
- example/main.go
- tools.go
- tools_test.go
- version.MD
* Feature: add Tools include some useful functions
* Feature: add Tools.PrettyJson used to pretty json format view in text
* Detail: use ctx.Tools() to use Tools
* 2020-05-10 15:00 at ShangHai
> add Tools include some useful functions

- example/router/main.go
- tree.go
- version.MD
* fix: fixed can not get correct Path which in Post requests
* 2020-08-11 18:00 at ShangHai
> fixed can not get correct Path which in Post requests

- cache/redis/cache_redis.go
- config/configs.go
- dotweb.go
- framework/redis/redisutil.go
- server.go
- session/session.go
- session/store_redis.go
- version.MD
* fix: fixed can not set redis maxIdle & maxActive when use redis session, fix for issue #236
* refactor: add StoreConfig.MaxIdle & StoreConfig.MaxActive set redis maxIdle & maxActive
* refactor: add redisutil.GetDefaultRedisClient to returns the RedisClient of specified address
* refactor: update redisutil.GetRedisClient returns the RedisClient of specified address & maxIdle & maxActive
* opt: set defaultMaxIdle=10, defaultMaxActive=50 when use default redis config
* How to set redis maxIdle & maxActive when use redis session:
~~~ go
sessionConf := session.NewDefaultRedisConfig("redis://xx.xx.xx.xx:6379/0")
sessionConf.BackupServerUrl = "redis://xx.xx.xx.xx:6379/0"
sessionConf.CookieName = "dotweb-example.SessionID"
sessionConf.MaxIdle = 20
sessionConf.MaxActive = 100
~~~
* 2020-12-19 …
> Version 1.7.14 fixed can not set redis maxIdle & maxActive when use redis session, fix for issue #236

- README.md
- context.go
- example/main.go
- example/middleware/main.go
- group.go
- middleware.go
- request.go
- router.go
- server.go
- tree.go
- version.MD
####Version 1.7.16
* Bug fix: fix middleware chain misbehaving in netsed groups
* Tips: for issue #234, thanks for @live's code
* Tips: replace *HttpContext to Context interface，used to implementation custom Context in dotweb
* feature: add ContextCreater func() Context & HttpServer.SetContextCreater
* refactor: update *HttpContext to Context interface in HttpServer & Middleware & Request
* refactor: add defaultContextCreater used to create Context with HttpContext when HttpServer.ServeHTTP
* example code: example/main.go
* How to use SetContextCreater:
~~~ go
// define
type testContext struct {
dotweb.HttpContext
TestInfo string
}
func testContextCreater() dotweb.Context {
return &testContext{TestInfo:"Test"}
}
// set into dotweb
app.HttpServer.SetContextCreater(testContextCreater)
// …
> Version 1.7.16: replace *HttpContext to Context interface & fix middleware chain misbehaving in netsed groups

- consts.go
- dotweb.go
- framework/crypto/cryptos.go
- framework/crypto/cryptos_test.go
- version.MD
####Version 1.7.17
* Bug fix: fix GetRandString return same result
* 2021-01-29 08:00 at ShangHai
> Bug fix: fix GetRandString return same result

- consts.go
- group.go
- version.MD
* Bug fix: fix deepcopy middleware not success
* 2021-04-20 13:00 at ShangHai
> Version 1.7.18: fix deepcopy middleware not success

- config/configs.go
- consts.go
- dotweb.go
- server.go
- version.MD
####Version 1.7.19 
* feature: add SetReadTimeout\SetReadHeaderTimeout\SetIdleTimeoutSetWriteTimeout func() in HttpServer
* 2021-04-20 13:00 at ShangHai
> add SetReadTimeout\SetReadHeaderTimeout\SetIdleTimeoutSetWriteTimeout

- framework/file/file.go
Signed-off-by: Abirdcfly <fp544037857@gmail.com>
> delete minor unreachable code caused by log.Fatal
